[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 115200
build_flags = 
    -Wall
    -Wextra
    -Wpedantic
    -Wshadow
    -Wdouble-promotion
    -Wunused-parameter
    -std=gnu++17
lib_deps = 
    ; suas libs existentes