[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino

monitor_speed = 115200

lib_ldf_mode = deep+
upload_port = dev/ttyACM1
build_flags =
    -std=gnu++14
    -DCORE_DEBUG_LEVEL=5
    -Iinclude
    ; raiz de lib/ para resolver HAL/interface, HAL/platform, HAL/board
    -Ilib
    ; diretórios dos drivers (para includes "XXXHal.h" e "LoRaCompatibility.h")
    -Ilib/Drivers/BMP280Hal
    -Ilib/Drivers/MPU9250Hal
    -Ilib/Drivers/SI7021Hal
    -Ilib/Drivers/CCS811Hal
    -Ilib/Drivers/DS3231Hal
    -Ilib/Drivers/SX127x

lib_deps =
    ; libs externas (baixadas da internet)
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit GFX Library @ ^1.12.4
    adafruit/Adafruit SSD1306 @ ^2.5.15

    ; drivers locais (força compilação e link)
    file://lib/Drivers/SX127x
    file://lib/Drivers/BMP280Hal
    file://lib/Drivers/MPU9250Hal
    file://lib/Drivers/SI7021Hal
    file://lib/Drivers/CCS811Hal
    file://lib/Drivers/DS3231Hal

upload_speed = 460800
board_build.filesystem = littlefs
upload_resetmethod = nodemcu
board_build.flash_mode = dio
