[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino

monitor_speed = 115200
monitor_filters = 
    esp32_exception_decoder
    default

; deep+ é essencial para achar includes aninhados
lib_ldf_mode = deep+

build_flags = 
    -std=gnu++14      
    -DCORE_DEBUG_LEVEL=5
    -Iinclude
    ; --- Flags para SX127x (debug) ---
    -DSX127X_DEBUG_REGISTERS
    -DSX127X_DEBUG_SPI

upload_speed = 460800

lib_deps = 
    ; --- Externas (Baixa da Internet) ---
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit GFX Library @ ^1.12.4
    adafruit/Adafruit SSD1306 @ ^2.5.15
    
    ; --- Driver LoRa Próprio (LOCAL) ---
    ./lib/Drivers/SX127x

    ; --- Seus HALs existentes ---
    MPU9250Hal=file://lib/Drivers/MPU9250Hal
    BMP280Hal=file://lib/Drivers/BMP280Hal
    SI7021Hal=file://lib/Drivers/SI7021Hal
    CCS811Hal=file://lib/Drivers/CCS811Hal
    DS3231Hal=file://lib/Drivers/DS3231Hal


board_build.filesystem = littlefs
upload_resetmethod = nodemcu
board_build.flash_mode = dio